### ISSUE TITLE
split up pistachio clk patch

### ISSUE THREAD

**Issue by Ham22** [CreatorDev/linux#3]
The pistachio clk patch contains a number of unrelated changes. It needs to be split into upstreamable changes and cleaned up.
Acceptance
- Must be in upstreamable state according to upstream rules
- Remove features that are not needed for base support (audio, wifi ...)
Will be part of the main PR Ian is arranging

**Comment by mtusnio** [comment]
Cleaned up CLK commits  - https://github.com/mtusnio/linux/commits/pistachio-clk-clean

**Comment by Ham22** [comment]
From what I can see in these commits we can just switch off frequency scaling and therefore not need these changes in "base  support"

**Comment by Ham22** [comment]
Cherry-picked the cleaned changes into https://github.com/CreatorDev/linux/tree/pistachio-4.9-wip and left for reference
